apiVersion: nais.io/v1
kind: Alert
metadata:
  name: yrkesskade-brevutsending
  namespace: yrkesskade
  labels:
    team: yrkesskade
spec:
  receivers:
    slack:
      channel: yrkesskade-alerts-prod
      prependText: "<!here> | "
  alerts:
    - alert: yrkesskade-brevutsending er nede
      description: App {{ $labels.app }} er nede i namespace {{ $labels.kubernetes_namespace }}
      expr: kube_deployment_status_replicas_available{deployment="yrkesskade-brevutsending"} == 0
      for: 2m
      action: "`kubectl describe pod {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for events, og `kubectl logs {{ $labels.kubernetes_pod_name }} -n {{ $labels.kubernetes_namespace }}` for logger"
      documentation: https://confluence.adeo.no/display/MAYYMYFSN/Drift+og+forvaltning
      sla: Responder innen 1 time i kontortid
      severity: danger