api:
  client:
    dokarkiv:
      clientId: prod-fss.teamdokumenthandtering.dokarkiv-q1
      url: https://dokarkiv.prod-fss-pub.nais.io
    dokdist:
      url: https://dokdistfordeling.prod-fss-pub.nais.io
    json-to-pdf:
      url: https://yrkesskade-json-to-pdf.intern.nav.no
    saf:
      clientId: prod-fss.teamdokumenthandtering.saf
      url: https://saf.prod-fss-pub.nais.io/graphql

spring:
  kafka:
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY}
      security.protocol: SSL
      basic:
        auth:
          credentials.source: USER_INFO
          user.info: ${KAFKA_SCHEMA_REGISTRY_USER}:${KAFKA_SCHEMA_REGISTRY_PASSWORD}
      ssl:
        truststore:
          type: JKS
          location: ${KAFKA_TRUSTSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        keystore:
          type: PKCS12
          location: ${KAFKA_KEYSTORE_PATH}
          password: ${KAFKA_CREDSTORE_PASSWORD}
        key.password: ${KAFKA_CREDSTORE_PASSWORD}

TENANT_ID: 62366534-1ec3-4962-8869-9b5535279d0b         # nav.no
no.nav.security.jwt:
  client:
    registration:
      saf-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.saf.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt
      dokarkiv-maskintilmaskin:
        token-endpoint-url: https://login.microsoftonline.com/${TENANT_ID}/oauth2/v2.0/token
        grant-type: client_credentials
        scope: api://${api.client.dokarkiv.clientId}/.default
        authentication:
          client-id: ${AZURE_APP_CLIENT_ID}
          client-jwk: ${AZURE_APP_JWK}
          client-auth-method: private_key_jwt