spring:
  application.name: yrkesskade-brevutsending
  autoconfigure.exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration
  kafka:
    bootstrap-servers: ${KAFKA_BROKERS}
    client-id: yrkesskade-brevutsending
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: yrkesskade-brevutsending
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: no.nav.yrkesskade.model
    listener:
      ack-mode: record
  main:
    banner-mode: "off"
  management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: info, health, metrics, prometheus
      base-path: /internal
      path-mapping.prometheus: prometheus
  metrics:
    export.prometheus.enabled: true
    tags:
      application: ${spring.application.name}

kafka:
  topic:
    brevutsendelse-bestilt: yrkesskade.privat-brevutsendelse-bestilt